services:
  # 1) Database
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  # 2) Banking API (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/bank_app
      - SECRET_KEY=supersecretkey
    expose:
      - "5000"         
    depends_on:
      - mongo
    restart: unless-stopped

  # 3) Transactions API (Node/Express)
  transactions:
    build:
      context: ./transactions
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/bank_app
      - PORT=4000
    expose:
      - "4000"      
    depends_on:
      - mongo
    restart: unless-stopped

  # 4) Frontend (studentportfolio)
  frontend:
    build:
      context: ./studentportfolio
      dockerfile: Dockerfile
    expose:
      - "80"        
    depends_on:
      - backend
    restart: unless-stopped

  # 5) Nginx reverse proxy (single public entrypoint)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"          
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - transactions
    restart: unless-stopped

volumes:
  mongo_data:
